services:
  app:
    build:
      dockerfile: ./Dockerfile
    networks:
      - appnet
    depends_on:
      - db
    expose:
      - "3000"
  
  nginx:
    image: nginx:latest
    networks:
      - appnet
    depends_on:
      - app
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
  
  db:
    image: mysql:latest
    networks:
      - appnet
    environment:
      - MYSQL_ROOT_PASSWORD=pass

networks:
  appnet:
    driver: bridge