services:
  app:
    build:
      dockerfile: ./Dockerfile
    networks:
      - appnet
    depends_on:
      - db
    expose:
      - "3000"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s npm start
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
  
  nginx:
    image: nginx:latest
    networks:
      - appnet
    depends_on:
      - app
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
  
  db:
    image: mysql:latest
    restart: always
    tty: true
    networks:
      - appnet
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdb
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  appnet:
    driver: bridge